### ISSUE TITLE
Export PDF's

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.election_day#51]

**Comment by msom** [comment]
We could use PhantomJS / Selenium to render the page to create the D3.js SVGs:

``` python
from selenium import webdriver

html = ''
try:
    driver = webdriver.PhantomJS()
    driver.set_window_size(1024, 768)
    driver.get(url)
    html = driver.page_source
finally:
    driver.quit()
```

And then create a styled PDF with reportlab.

**Comment by href** [comment]
We did the same thing a while ago in ocqms. There we just use nodejs. Since we need it anyway for phantomjs I would suggest we render it by calling node directly, instead of going through Selenium, which by itself is a pretty huge thing to run on a server (big java runtime eating loads of memory).

Node can be installed in a virtualenv: https://pypi.python.org/pypi/nodeenv

However I've discussed it with @treinhard and it might make sense to introduce a microservice for this. Here, as well as in ocqms we need two things:
- Render D3 on the server side to SVG.
- Render SVG to PDF.

This seems like a good reason for a microservice that receives some D3 js script, and returns it in SVG/PDF form. Of course, only if the user is authenticated.

This service could be written directly in node. No reason to pump this through Python.

Of course this microservice would be running on its own server. If we want to be extra fancy we could even aim for an Amazon Lambda deployment: https://aws.amazon.com/lambda/details/
